---
- name: OS-specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - vars
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_lsb.id }}.yml"

- name: Create system directory
  ansible.builtin.file:
    path: "{{ borgbackup_system_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create repo directory
  ansible.builtin.file:
    path: "{{ borgbackup_system_directory }}/repo"
    state: directory
    owner: root
    group: root
    mode: "0755"

- include_tasks: user.yml
  when: borgbackup_user != ""

- include_tasks: client.yml
  when: borgbackup_data_directory != ""

- name: OS-specific tasks
  include_tasks: "{{ lookup('first_found', tasks) }}"
  vars:
    tasks:
      paths:
        - tasks
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_lsb.id }}.yml"

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ borgbackup_dependencies }}"
    state: present

- name: Install via pip
  include_tasks: pip.yml
  when: borgbackup_pip | default(borgbackup_pip_dist) | default(false)

- name: Install via package
  ansible.builtin.package:
    name:
      - "{{ borgbackup_package }}"
    state: present
  when: not (borgbackup_pip | default(borgbackup_pip_dist) | default(false))
