---
- name: Create system directory
  file:
    path: "{{ borgbackup_system_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create repo directory
  file:
    path: "{{ borgbackup_system_directory }}/repo"
    state: directory
    owner: root
    group: root
    mode: "0755"

- include_tasks: user.yml
  when: borgbackup_user != ""

- include_tasks: client.yml
  when: borgbackup_data_directory != ""

- name: OS-specific tasks
  include_tasks: "{{ lookup('first_found', tasks) }}"
  vars:
    tasks:
      paths:
        - tasks
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_lsb.id }}.yml"
